[package]
name = "aoc-2016"
version = "0.1.0"
authors = ["Ilya Linnik <thenixan@yandex-team.ru>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
md5 = "0.7.0"
iterslide = "1.0.1"
regex = "1.3.1"